### ISSUE TITLE
Tabs created from pinned tabs are not processed

### ISSUE THREAD

**Issue by basilevs** [basilevs/reusetab-firefox#11]
# Test steps
- Pin Gmail
- Pin issue tracker
- Open issue notification in Gmail
- Open notification in a new tab

## Expected
Tab is closed, pinned issue tracker is reused

## Actual
New tab shows issue, tracker tab is unchanged.

**Comment by basilevs** [comment]
A new tab should be active for the issue to be reproduced.
tabs.Tab.lastAccessed field changes unexpectedly without any user interaction. Need to find more documentation on that.
Some information (not enough) is found in [bug 1356879](https://bugzilla.mozilla.org/show_bug.cgi?id=1356879)

**Comment by basilevs** [comment]
Fixed in https://github.com/basilevs/reusetab-firefox/releases/tag/0.8
The fix depends on a time elapsed since new tab creation to determine if a tab navigates automatically. This is a horrible timing-sensitive strategy.

**Comment by lfr** [comment]
I believe this fix may have made the extension unreliable, when opening tabs in quick succession, only one out of two re-uses the pinned tab.

**Comment by basilevs** [comment]
> I believe this fix may have made the extension unreliable, when opening tabs in quick succession, only one out of two re-uses the pinned tab.

Thanks for the report. I will review the solution with this scenario in mind.

**Comment by basilevs** [comment]
I'm unable to test at the moment, but the code change seem to have an opposite effect - unreliable behavior was observed before the change and was eliminated after. 

@lfr Could you please confirm, that you can actually reproduce the problem and provide test steps (secifically what site do you use for the test and how duplicate tabs are opened)?

**Comment by lfr** [comment]
Hello @basilevs, I will not be using this extension anymore as it doesn't suit my particular workflow (only works on pinned tabs, see #20). I only use it for Jira, I have my notifications in firefox's side-view and as I click on them they'll often re-use the pinned tab but I'd say 1 out of 5 times they open a new tab.

If I click notifications links in quick succession, I think 1 out of 2 opens in a new tab, which is why I believe this issue is timing-related.

In any case I didn't want to use a pinned tab for this purpose, so since I won't be using the extension, I suggest closing this until someone else bumps into the issue.
